---
# noqa: var-naming[no-role-prefix]

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-CentOS-Official"
  download_policy: "{{ foreman_products_defaults_download_policy_centos_stream8 }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_centos_stream8 }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_centos_stream8 | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_centos_stream8 }}"
  unprotected: "{{ foreman_products_defaults_unprotected_centos_stream8 | bool }}"


foreman_products_defaults_centos_stream8_sig_virtualization: &foreman_products_defaults_centos_stream8_sig_virtualization
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_centos_stream8_sig_virtualization }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_centos_stream8_sig_virtualization }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_centos_stream8_sig_virtualization | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_centos_stream8_sig_virtualization }}"
  unprotected: "{{ foreman_products_defaults_unprotected_centos_stream8_sig_virtualization | bool }}"


foreman_products_centos_stream8_sig_virtualization_advanced_virtualization:
  - name: "{{ foreman_product_name_prefix | default('') }}CentOS"
    label: "{{ foreman_product_label_prefix | default('') }}CentOS"
    organization: "{{ foreman_organization_centos_stream8_sig_virtualization_advanced_virtualization }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 8 - Advanced Virtualization"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-stream-8-advanced-virtualization"
        <<: *foreman_products_defaults_centos_stream8_sig_virtualization
        url: "{{ foreman_repo_baseurl_centos_stream8 }}/8-stream/virt/x86_64/advancedvirt-common/"
        gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-CentOS-SIG-Virtualization"
        organization: "{{ foreman_organization_centos_stream8_sig_virtualization_advanced_virtualization }}"

foreman_products_centos_stream8_sig_virtualization_ovirt44:
  - name: "{{ foreman_product_name_prefix | default('') }}CentOS"
    label: "{{ foreman_product_label_prefix | default('') }}CentOS"
    organization: "{{ foreman_organization_centos_stream8_sig_virtualization_ovirt44 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS 8 - oVirt 4.4"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-8-ovirt44"
        <<: *foreman_products_defaults_centos_stream8_sig_virtualization
        url: "{{ foreman_repo_baseurl_centos8 }}/8/virt/x86_64/ovirt-44/"
        gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-CentOS-SIG-Virtualization"
        organization: "{{ foreman_organization_centos_stream8_sig_virtualization_ovirt44 }}"

foreman_products_centos_stream8_sig_virtualization_ovirt45:
  - name: "{{ foreman_product_name_prefix | default('') }}CentOS"
    label: "{{ foreman_product_label_prefix | default('') }}CentOS"
    organization: "{{ foreman_organization_centos_stream8_sig_virtualization_ovirt45 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 8 - oVirt 4.5"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-stream-8-ovirt45"
        <<: *foreman_products_defaults_centos_stream8_sig_virtualization
        url: "{{ foreman_repo_baseurl_centos_stream8 }}/8-stream/virt/x86_64/ovirt-45/"
        gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-CentOS-SIG-Virtualization"
        organization: "{{ foreman_organization_centos_stream8_sig_virtualization_ovirt45 }}"
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 8 - oVirt 4.5 - OpenStack Yoga Repository"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-stream-8-ovirt45-openstack-yoga"
        <<: *foreman_products_defaults_centos_stream8_sig_virtualization
        url: "{{ foreman_repo_baseurl_centos_stream8 }}/8-stream/cloud/x86_64/openstack-yoga/"
        gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-CentOS-SIG-Cloud"
        organization: "{{ foreman_organization_centos_stream8_sig_virtualization_ovirt45 }}"
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 8 - oVirt 4.5 - upstream"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-stream-8-ovirt45-upstream"
        <<: *foreman_products_defaults_centos_stream8_sig_virtualization
        url: "{{ foreman_repo_baseurl_ovirt }}/pub/ovirt-4.5/rpm/el8/"
        gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-oVirt-4.5"
        organization: "{{ foreman_organization_centos_stream8_sig_virtualization_ovirt45 }}"

foreman_products_centos_stream8_sig_virtualization: "{{ [] |
  union( foreman_products_centos_stream8_sig_virtualization_advanced_virtualization | default([]) if foreman_enable_centos_stream8_sig_virtualization_advanced_virtualization else [] ) |
  union( foreman_products_centos_stream8_sig_virtualization_ovirt44 | default([]) if foreman_enable_centos_stream8_sig_virtualization_ovirt44 else [] ) |
  union( foreman_products_centos_stream8_sig_virtualization_ovirt45 | default([]) if foreman_enable_centos_stream8_sig_virtualization_ovirt45 else [] )
  }}"


foreman_content_views_centos_stream8_sig_virtualization_advanced_virtualization:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream8_advanced_virtualization"
    organization: "{{ foreman_organization_centos_stream8_sig_virtualization_advanced_virtualization }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 8 - Advanced Virtualization"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos_stream8_sig_virtualization_advanced_virtualization }}"

foreman_content_views_centos_stream8_sig_virtualization_ovirt44:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream8_ovirt44"
    organization: "{{ foreman_organization_centos_stream8_sig_virtualization_ovirt44 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS 8 - oVirt 4.4"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos_stream8_sig_virtualization_ovirt44 }}"

foreman_content_views_centos_stream8_sig_virtualization_ovirt45:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream8_ovirt45"
    organization: "{{ foreman_organization_centos_stream8_sig_virtualization_ovirt45 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 8 - oVirt 4.5"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos_stream8_sig_virtualization_ovirt45 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream8_ovirt45"
    organization: "{{ foreman_organization_centos_stream8_sig_virtualization_ovirt45 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 8 - oVirt 4.5 - OpenStack Yoga Repository"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos_stream8_sig_virtualization_ovirt45 }}"
    filters:
      - name: "CentOS Stream 8 - oVirt 4.5 - OpenStack Yoga Repository exclude filter"
        filter_type: "rpm"
        rule_name: ansible
      - name: "CentOS Stream 8 - oVirt 4.5 - OpenStack Yoga Repository exclude filter"
        filter_type: "rpm"
        rule_name: ansible-test
      - name: "CentOS Stream 8 - oVirt 4.5 - OpenStack Yoga Repository exclude filter"
        filter_type: "rpm"
        rule_name: openstack-ansible-core
      - name: "CentOS Stream 8 - oVirt 4.5 - OpenStack Yoga Repository exclude filter"
        filter_type: "rpm"
        rule_name: python3-rdo-openvswitch
      - name: "CentOS Stream 8 - oVirt 4.5 - OpenStack Yoga Repository exclude filter"
        filter_type: "rpm"
        rule_name: rdo-openvswitch
      - name: "CentOS Stream 8 - oVirt 4.5 - OpenStack Yoga Repository exclude filter"
        filter_type: "rpm"
        rule_name: rdo-ovn
      - name: "CentOS Stream 8 - oVirt 4.5 - OpenStack Yoga Repository exclude filter"
        filter_type: "rpm"
        rule_name: rdo-ovn-central
      - name: "CentOS Stream 8 - oVirt 4.5 - OpenStack Yoga Repository exclude filter"
        filter_type: "rpm"
        rule_name: rdo-ovn-host
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream8_ovirt45_upstream"
    organization: "{{ foreman_organization_centos_stream8_sig_virtualization_ovirt45 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 8 - oVirt 4.5 - upstream"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos_stream8_sig_virtualization_ovirt45 }}"

foreman_content_views_centos_stream8_sig_virtualization: "{{ [] |
  union( foreman_content_views_centos_stream8_sig_virtualization_advanced_virtualization | default([]) if foreman_enable_centos_stream8_sig_virtualization_advanced_virtualization else [] ) |
  union( foreman_content_views_centos_stream8_sig_virtualization_ovirt44 | default([]) if foreman_enable_centos_stream8_sig_virtualization_ovirt44 else [] ) |
  union( foreman_content_views_centos_stream8_sig_virtualization_ovirt45 | default([]) if foreman_enable_centos_stream8_sig_virtualization_ovirt45 else [] )
  }}"

