---
# noqa: var-naming[no-role-prefix]

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-CentOS-Official"
  download_policy: "{{ foreman_products_defaults_download_policy_centos_stream8 }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_centos_stream8 }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_centos_stream8 | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_centos_stream8 }}"
  unprotected: "{{ foreman_products_defaults_unprotected_centos_stream8 | bool }}"


foreman_products_defaults_centos_stream8_sig_hyperscale: &foreman_products_defaults_centos_stream8_sig_hyperscale
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_centos_stream8_sig_hyperscale }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_centos_stream8_sig_hyperscale }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_centos_stream8_sig_hyperscale | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_centos_stream8_sig_hyperscale }}"
  unprotected: "{{ foreman_products_defaults_unprotected_centos_stream8_sig_hyperscale | bool }}"


foreman_products_centos_stream8_sig_hyperscale_main:
  - name: "{{ foreman_product_name_prefix | default('') }}CentOS"
    label: "{{ foreman_product_label_prefix | default('') }}CentOS"
    organization: "{{ foreman_organization_centos_stream8_sig_hyperscale_main }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 8 - Hyperscale"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-stream-8-hyperscale"
        <<: *foreman_products_defaults_centos_stream8_sig_hyperscale
        url: "{{ foreman_repo_baseurl_centos_stream8 }}/8-stream/hyperscale/x86_64/packages-main/"
        gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-CentOS-SIG-HyperScale"
        organization: "{{ foreman_organization_centos_stream8_sig_hyperscale_main }}"

foreman_products_centos_stream8_sig_hyperscale_hotfixes:
  - name: "{{ foreman_product_name_prefix | default('') }}CentOS"
    label: "{{ foreman_product_label_prefix | default('') }}CentOS"
    organization: "{{ foreman_organization_centos_stream8_sig_hyperscale_hotfixes }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 8 - Hyperscale Hotfixes"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-stream-8-hyperscale-hotfixes"
        <<: *foreman_products_defaults_centos_stream8_sig_hyperscale
        url: "{{ foreman_repo_baseurl_centos_stream8 }}/8-stream/hyperscale/x86_64/packages-hotfixes/"
        gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-CentOS-SIG-HyperScale"
        organization: "{{ foreman_organization_centos_stream8_sig_hyperscale_hotfixes }}"

foreman_products_centos_stream8_sig_hyperscale_spin:
  - name: "{{ foreman_product_name_prefix | default('') }}CentOS"
    label: "{{ foreman_product_label_prefix | default('') }}CentOS"
    organization: "{{ foreman_organization_centos_stream8_sig_hyperscale_spin }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 8 - Hyperscale Spin"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-stream-8-hyperscale-spin"
        <<: *foreman_products_defaults_centos_stream8_sig_hyperscale
        url: "{{ foreman_repo_baseurl_centos_stream8 }}/8-stream/hyperscale/x86_64/packages-spin/"
        gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-CentOS-SIG-HyperScale"
        organization: "{{ foreman_organization_centos_stream8_sig_hyperscale_spin }}"

foreman_products_centos_stream8_sig_hyperscale_experimental:
  - name: "{{ foreman_product_name_prefix | default('') }}CentOS"
    label: "{{ foreman_product_label_prefix | default('') }}CentOS"
    organization: "{{ foreman_organization_centos_stream8_sig_hyperscale_experimental }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 8 - Hyperscale Experimental"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-stream-8-hyperscale-experimental"
        <<: *foreman_products_defaults_centos_stream8_sig_hyperscale
        url: "{{ foreman_repo_baseurl_centos_stream8 }}/8-stream/hyperscale/x86_64/packages-experimental/"
        gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-CentOS-SIG-HyperScale"
        organization: "{{ foreman_organization_centos_stream8_sig_hyperscale_experimental }}"

foreman_products_centos_stream8_sig_virtualization: "{{ [] |
  union( foreman_products_centos_stream8_sig_hyperscale_main | default([]) if foreman_enable_centos_stream8_sig_hyperscale_main else [] ) |
  union( foreman_products_centos_stream8_sig_hyperscale_hotfixes | default([]) if foreman_enable_centos_stream8_sig_hyperscale_hotfixes else [] ) |
  union( foreman_products_centos_stream8_sig_hyperscale_spin | default([]) if foreman_enable_centos_stream8_sig_hyperscale_spin else [] ) |
  union( foreman_products_centos_stream8_sig_hyperscale_experimental | default([]) if foreman_enable_centos_stream8_sig_hyperscale_experimental else [] )
  }}"


foreman_content_views_centos_stream8_sig_hyperscale_main:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream8_hyperscale"
    organization: "{{ foreman_organization_centos_stream8_sig_hyperscale_main }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 8 - Hyperscale"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos_stream8_sig_hyperscale_main }}"

foreman_content_views_centos_stream8_sig_hyperscale_hotfixes:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream8_hyperscale_hotfixes"
    organization: "{{ foreman_organization_centos_stream8_sig_hyperscale_hotfixes }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 8 - Hyperscale Hotfixes"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos_stream8_sig_hyperscale_hotfixes }}"

foreman_content_views_centos_stream8_sig_hyperscale_spin:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream8_hyperscale_spin"
    organization: "{{ foreman_organization_centos_stream8_sig_hyperscale_spin }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 8 - Hyperscale Spin"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos_stream8_sig_hyperscale_spin }}"

foreman_content_views_centos_stream8_sig_hyperscale_experimental:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream8_hyperscale_experimental"
    organization: "{{ foreman_organization_centos_stream8_sig_hyperscale_experimental }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 8 - Hyperscale Experimental"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos_stream8_sig_hyperscale_experimental }}"

foreman_content_views_centos_stream8_sig_virtualization: "{{ [] |
  union( foreman_content_views_centos_stream8_sig_hyperscale_main | default([]) if foreman_enable_centos_stream8_sig_hyperscale_main else [] ) |
  union( foreman_content_views_centos_stream8_sig_hyperscale_hotfixes | default([]) if foreman_enable_centos_stream8_sig_hyperscale_hotfixes else [] ) |
  union( foreman_content_views_centos_stream8_sig_hyperscale_spin | default([]) if foreman_enable_centos_stream8_sig_hyperscale_spin else [] ) |
  union( foreman_content_views_centos_stream8_sig_hyperscale_experimental | default([]) if foreman_enable_centos_stream8_sig_hyperscale_experimental else [] )
  }}"

