---
# noqa: var-naming[no-role-prefix]

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-CentOS-Official"
  download_policy: "{{ foreman_products_defaults_download_policy_centos8 }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_centos8 }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_centos8 | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_centos8 }}"
  unprotected: "{{ foreman_products_defaults_unprotected_centos8 | bool }}"


foreman_products_defaults_centos8_sig_kmods: &foreman_products_defaults_centos8_sig_kmods
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_centos8_sig_kmods }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_centos8_sig_kmods }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_centos8_sig_kmods | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_centos8_sig_kmods }}"
  unprotected: "{{ foreman_products_defaults_unprotected_centos8_sig_kmods | bool }}"


foreman_products_centos8_sig_kmods_main:
  - name: "{{ foreman_product_name_prefix | default('') }}CentOS"
    label: "{{ foreman_product_label_prefix | default('') }}CentOS"
    organization: "{{ foreman_organization_centos8_sig_kmods_main }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS 8 - Kmods"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-8-kmods"
        <<: *foreman_products_defaults_centos8_sig_kmods
        url: "{{ foreman_repo_baseurl_centos8 }}/8/kmods/x86_64/packages-main/"
        gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-CentOS-SIG-Kmods"
        organization: "{{ foreman_organization_centos8_sig_kmods_main }}"

foreman_products_centos8_sig_kmods_rebuild:
  - name: "{{ foreman_product_name_prefix | default('') }}CentOS"
    label: "{{ foreman_product_label_prefix | default('') }}CentOS"
    organization: "{{ foreman_organization_centos8_sig_kmods_rebuild }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS 8 - Kmods - Rebuild"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-8-kmods-rebuild"
        <<: *foreman_products_defaults_centos8_sig_kmods
        url: "{{ foreman_repo_baseurl_centos8 }}/8/kmods/x86_64/packages-rebuild/"
        gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-CentOS-SIG-Kmods"
        organization: "{{ foreman_organization_centos8_sig_kmods_rebuild }}"

foreman_products_centos8_sig_kmods: "{{ [] |
  union( foreman_products_centos8_sig_kmods_main | default([]) if foreman_enable_centos8_sig_kmods_main else [] ) |
  union( foreman_products_centos8_sig_kmods_rebuild | default([]) if foreman_enable_centos8_sig_kmods_rebuild else [] )
  }}"


foreman_content_views_centos8_sig_kmods_main:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos8_kmods"
    organization: "{{ foreman_organization_centos8_sig_kmods_main }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS 8 - Kmods"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos8_sig_kmods_main }}"

foreman_content_views_centos8_sig_kmods_rebuild:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos8_kmods_rebuild"
    organization: "{{ foreman_organization_centos8_sig_kmods_rebuild }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS 8 - Kmods - Rebuild"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos8_sig_kmods_rebuild }}"

foreman_content_views_centos8_sig_kmods: "{{ [] |
  union( foreman_content_views_centos8_sig_kmods_main | default([]) if foreman_enable_centos8_sig_kmods_main else [] ) |
  union( foreman_content_views_centos8_sig_kmods_rebuild | default([]) if foreman_enable_centos8_sig_kmods_rebuild else [] )
  }}"

