---
# noqa: var-naming[no-role-prefix]

foreman_content_credentials_centos_stream9: []


foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-CentOS-Official"
  download_policy: "{{ foreman_products_defaults_download_policy_centos_stream9 }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_centos_stream9 }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_centos_stream9 | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_centos_stream9 }}"
  unprotected: "{{ foreman_products_defaults_unprotected_centos_stream9 | bool }}"


foreman_products_centos_stream9:
  - name: "{{ foreman_product_name_prefix | default('') }}CentOS"
    label: "{{ foreman_product_label_prefix | default('') }}CentOS"
    organization: "{{ foreman_organization_centos_stream9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 9 - BaseOS"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-stream-9-baseos"
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_stream9 }}/9-stream/BaseOS/x86_64/os/"
        organization: "{{ foreman_organization_centos_stream9 }}"
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 9 - AppStream"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-stream-9-appstream"
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_stream9 }}/9-stream/AppStream/x86_64/os/"
        organization: "{{ foreman_organization_centos_stream9 }}"

      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 9 - CRB"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-stream-9-crb"
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_stream9 }}/9-stream/CRB/x86_64/os/"
        organization: "{{ foreman_organization_centos_stream9 }}"

      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 9 - HighAvailability"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-stream-9-highavailability"
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_stream9 }}/9-stream/HighAvailability/x86_64/os/"
        organization: "{{ foreman_organization_centos_stream9 }}"
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 9 - NFV"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-stream-9-nfv"
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_stream9 }}/9-stream/NFV/x86_64/os/"
        organization: "{{ foreman_organization_centos_stream9 }}"
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 9 - RealTime"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-stream-9-rt"
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_stream9 }}/9-stream/RT/x86_64/os/"
        organization: "{{ foreman_organization_centos_stream9 }}"
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 9 - ResilientStorage"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-stream-9-resilientstorage"
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_stream9 }}/9-stream/ResilientStorage/x86_64/os/"
        organization: "{{ foreman_organization_centos_stream9 }}"

      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 9 - Extras packages"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-stream-9-extras-common"
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_stream9 }}/SIGs/9-stream/extras/x86_64/extras-common/"
        gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-CentOS-SIG-Extras"
        organization: "{{ foreman_organization_centos_stream9 }}"

foreman_products_centos_stream9_kickstart:
  - name: "{{ foreman_product_name_prefix | default('') }}CentOS"
    label: "{{ foreman_product_label_prefix | default('') }}CentOS"
    organization: "{{ foreman_organization_centos_stream9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 9 - BaseOS"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-stream-9-baseos"
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_stream9 }}/9-stream/BaseOS/x86_64/os/"
        organization: "{{ foreman_organization_centos_stream9 }}"
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 9 - AppStream"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-stream-9-appstream"
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_stream9 }}/9-stream/AppStream/x86_64/os/"
        organization: "{{ foreman_organization_centos_stream9 }}"


foreman_content_views_centos_stream9:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream9_baseos"
    organization: "{{ foreman_organization_centos_stream9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 9 - BaseOS"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos_stream9 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream9_appstream"
    organization: "{{ foreman_organization_centos_stream9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 9 - AppStream"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos_stream9 }}"

  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream9_crb"
    organization: "{{ foreman_organization_centos_stream9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 9 - CRB"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos_stream9 }}"

  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream9_highavailability"
    organization: "{{ foreman_organization_centos_stream9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 9 - HighAvailability"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos_stream9 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream9_nfv"
    organization: "{{ foreman_organization_centos_stream9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 9 - NFV"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos_stream9 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream9_rt"
    organization: "{{ foreman_organization_centos_stream9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 9 - RealTime"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos_stream9 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream9_resilientstorage"
    organization: "{{ foreman_organization_centos_stream9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 9 - ResilientStorage"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos_stream9 }}"

  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream9_extras_common"
    organization: "{{ foreman_organization_centos_stream9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 9 - Extras packages"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos_stream9 }}"

foreman_composite_content_views_centos_stream9:
  - name: "{{ foreman_ccv_prefix | default('ccv_') }}{{ foreman_ccv_name_prefix | default('') }}centos_stream9"
    organization: "{{ foreman_organization_centos_stream9 }}"
    composite: True
    allow_promote: "{{ foreman_ccv_allow_promote_centos_stream9 }}"
    auto_publish: "{{ foreman_ccv_auto_publish_centos_stream9 }}"
    components:
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream9_baseos"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream9_appstream"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream9_crb"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream9_highavailability"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream9_nfv"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream9_rt"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream9_resilientstorage"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream9_extras_common"
        latest: true


foreman_operatingsystems_defaults: &foreman_operatingsystems_defaults
  os_family: "Redhat"
  password_hash: "SHA512"
  architectures:
    - x86_64
  # ptables:
  #   - Kickstart default
  #   - Kickstart custom
  ptables: "{{
    [ 'Kickstart default',
      'Kickstart custom' ] |
      union( foreman_partition_tables | default([]) | selectattr('os_family', 'defined') | selectattr('os_family', '==', 'Redhat') | map(attribute='name') | list )
    }}"


foreman_operatingsystems_centos_stream9:
  - name: "CentOS_Stream"
    major: "9"
    minor: ""
    description: "CentOS Stream release 9"
    default_templates: "{{ foreman_operatingsystems_centos_stream9_default_templates | default( foreman_operatingsystems_centos_default_templates | default( foreman_operatingsystems_el_default_templates | default([]) ) ) }}"
    <<: *foreman_operatingsystems_defaults


foreman_installation_media_defaults: &foreman_installation_media_defaults
  os_family: Redhat
  # organizations:
  #   - "{{ foreman_organization }}"
  # locations:
  #   - "{{ foreman_default_location }}"
  organizations: "{{ foreman_all_organizations_namelist }}"
  locations: "{{ foreman_all_locations_namelist }}"


foreman_installation_media_centos_stream9:
  - name: "{{ foreman_media_name_prefix | default('') }}CentOS Stream 9 BaseOS"
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/CentOS/centos-stream-9-baseos/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - CentOS Stream release 9
  - name: "{{ foreman_media_name_prefix | default('') }}CentOS Stream 9 AppStream"
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/CentOS/centos-stream-9-appstream/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - CentOS Stream release 9


foreman_activation_keys_defaults: &foreman_activation_keys_defaults
  # lifecycle_environment: "Library"
  # subscriptions:
  #   - name: "CentOS"
  #   - name: "Extra Packages for Enterprise Linux"
  #   # - name: "Foreman"
  auto_attach: False
  # release_version: 9
  # service_level: Standard


foreman_activation_keys_centos_stream9:
  - name: "{{ foreman_ak_prefix | default('ak_') }}{{ foreman_ak_name_prefix | default('') }}centos9stream"
    organization: "{{ foreman_organization_centos_stream9 }}"
    content_view: "{{ foreman_ccv_prefix | default('ccv_') }}{{ foreman_ccv_name_prefix | default('') }}centos_stream9"
    <<: *foreman_activation_keys_defaults
    content_overrides:
      - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}CentOS_{{ foreman_repo_label_prefix | default('') }}centos-stream-9-baseos"
        override: default
      - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}CentOS_{{ foreman_repo_label_prefix | default('') }}centos-stream-9-appstream"
        override: default
      - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}CentOS_{{ foreman_repo_label_prefix | default('') }}centos-stream-9-crb"
        override: disabled
      - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}CentOS_{{ foreman_repo_label_prefix | default('') }}centos-stream-9-highavailability"
        override: disabled
      - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}CentOS_{{ foreman_repo_label_prefix | default('') }}centos-stream-9-nfv"
        override: disabled
      - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}CentOS_{{ foreman_repo_label_prefix | default('') }}centos-stream-9-rt"
        override: disabled
      - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}CentOS_{{ foreman_repo_label_prefix | default('') }}centos-stream-9-resilientstorage"
        override: disabled
      - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}CentOS_{{ foreman_repo_label_prefix | default('') }}centos-stream-9-extras-common"
        override: disabled


foreman_sync_plan_products_centos_stream9: []

