---
# noqa: var-naming[no-role-prefix]

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-CentOS-Official"
  download_policy: "{{ foreman_products_defaults_download_policy_centos8 }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_centos8 }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_centos8 | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_centos8 }}"
  unprotected: "{{ foreman_products_defaults_unprotected_centos8 | bool }}"


foreman_products_defaults_centos8_sig_configmanagement: &foreman_products_defaults_centos8_sig_configmanagement
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_centos8_sig_configmanagement }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_centos8_sig_configmanagement }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_centos8_sig_configmanagement | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_centos8_sig_configmanagement }}"
  unprotected: "{{ foreman_products_defaults_unprotected_centos8_sig_configmanagement | bool }}"


foreman_products_centos8_sig_configmanagement_ansible29:
  - name: "{{ foreman_product_name_prefix | default('') }}CentOS"
    label: "{{ foreman_product_label_prefix | default('') }}CentOS"
    organization: "{{ foreman_organization_centos8_sig_configmanagement_ansible29 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS 8 - Configmanagement SIG - ansible-29"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-8-ansible-29"
        <<: *foreman_products_defaults_centos8_sig_configmanagement
        url: "{{ foreman_repo_baseurl_centos8 }}/8/configmanagement/x86_64/ansible-29/"
        gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-CentOS-SIG-ConfigManagement"
        organization: "{{ foreman_organization_centos8_sig_configmanagement_ansible29 }}"

foreman_products_centos8_sig_configmanagement: "{{ [] |
  union( foreman_products_centos8_sig_configmanagement_ansible29 | default([]) if foreman_enable_centos8_sig_configmanagement_ansible29 else [] )
  }}"


foreman_content_views_centos8_sig_configmanagement_ansible29:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos8_ansible_29"
    organization: "{{ foreman_organization_centos8_sig_configmanagement_ansible29 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS 8 - Configmanagement SIG - ansible-29"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos8_sig_configmanagement_ansible29 }}"

foreman_content_views_centos8_sig_configmanagement: "{{ [] |
  union( foreman_content_views_centos8_sig_configmanagement_ansible29 | default([]) if foreman_enable_centos8_sig_configmanagement_ansible29 else [] )
  }}"

