---
# noqa: var-naming[no-role-prefix]

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-CentOS-Official"
  download_policy: "{{ foreman_products_defaults_download_policy_centos_stream9 }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_centos_stream9 }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_centos_stream9 | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_centos_stream9 }}"
  unprotected: "{{ foreman_products_defaults_unprotected_centos_stream9 | bool }}"


foreman_products_defaults_centos_stream9_sig_kmods: &foreman_products_defaults_centos_stream9_sig_kmods
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_centos_stream9_sig_kmods }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_centos_stream9_sig_kmods }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_centos_stream9_sig_kmods | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_centos_stream9_sig_kmods }}"
  unprotected: "{{ foreman_products_defaults_unprotected_centos_stream9_sig_kmods | bool }}"


foreman_products_centos_stream9_sig_kmods_main:
  - name: "{{ foreman_product_name_prefix | default('') }}CentOS"
    label: "{{ foreman_product_label_prefix | default('') }}CentOS"
    organization: "{{ foreman_organization_centos_stream9_sig_kmods_main }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 9 - Kmods"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-stream-9-kmods"
        <<: *foreman_products_defaults_centos_stream9_sig_kmods
        url: "{{ foreman_repo_baseurl_centos_stream9 }}/SIGs/9-stream/kmods/x86_64/packages-main"
        gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-CentOS-SIG-Kmods"
        organization: "{{ foreman_organization_centos_stream9_sig_kmods_main }}"

foreman_products_centos_stream9_sig_kmods_rebuild:
  - name: "{{ foreman_product_name_prefix | default('') }}CentOS"
    label: "{{ foreman_product_label_prefix | default('') }}CentOS"
    organization: "{{ foreman_organization_centos_stream9_sig_kmods_rebuild }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 9 - Kmods - Rebuild"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-stream-9-kmods-rebuild"
        <<: *foreman_products_defaults_centos_stream9_sig_kmods
        url: "{{ foreman_repo_baseurl_centos_stream9 }}/SIGs/9-stream/kmods/x86_64/packages-rebuild"
        gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-CentOS-SIG-Kmods"
        organization: "{{ foreman_organization_centos_stream9_sig_kmods_rebuild }}"

foreman_products_centos_stream9_sig_kmods_userspace:
  - name: "{{ foreman_product_name_prefix | default('') }}CentOS"
    label: "{{ foreman_product_label_prefix | default('') }}CentOS"
    organization: "{{ foreman_organization_centos_stream9_sig_kmods_userspace }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 9 - Kmods - User Space"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-stream-9-kmods-userspace"
        <<: *foreman_products_defaults_centos_stream9_sig_kmods
        url: "{{ foreman_repo_baseurl_centos_stream9 }}/SIGs/9-stream/kmods/x86_64/packages-userspace"
        gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-CentOS-SIG-Kmods"
        organization: "{{ foreman_organization_centos_stream9_sig_kmods_userspace }}"

foreman_products_centos_stream9_sig_kmods: "{{ [] |
  union( foreman_products_centos_stream9_sig_kmods_main | default([]) if foreman_enable_centos_stream9_sig_kmods_main else [] ) |
  union( foreman_products_centos_stream9_sig_kmods_rebuild | default([]) if foreman_enable_centos_stream9_sig_kmods_rebuild else [] ) |
  union( foreman_products_centos_stream9_sig_kmods_userspace | default([]) if foreman_enable_centos_stream9_sig_kmods_userspace else [] )
  }}"


foreman_content_views_centos_stream9_sig_kmods_main:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream9_kmods"
    organization: "{{ foreman_organization_centos_stream9_sig_kmods_main }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 9 - Kmods"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos_stream9_sig_kmods_main }}"

foreman_content_views_centos_stream9_sig_kmods_rebuild:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream9_kmods_rebuild"
    organization: "{{ foreman_organization_centos_stream9_sig_kmods_rebuild }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 9 - Kmods - Rebuild"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos_stream9_sig_kmods_rebuild }}"

foreman_content_views_centos_stream9_sig_kmods_userspace:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos_stream9_kmods_userspace"
    organization: "{{ foreman_organization_centos_stream9_sig_kmods_userspace }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS Stream 9 - Kmods - User Space"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos_stream9_sig_kmods_userspace }}"

foreman_content_views_centos_stream9_sig_kmods: "{{ [] |
  union( foreman_content_views_centos_stream9_sig_kmods_main | default([]) if foreman_enable_centos_stream9_sig_kmods_main else [] ) |
  union( foreman_content_views_centos_stream9_sig_kmods_rebuild | default([]) if foreman_enable_centos_stream9_sig_kmods_rebuild else [] ) |
  union( foreman_content_views_centos_stream9_sig_kmods_userspace | default([]) if foreman_enable_centos_stream9_sig_kmods_userspace else [] )
  }}"

